name: Monthly Undefined Repo Owner Report

on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dotenv openpyxl

      - name: Run the script
        env:
          GIT_API_KEY: ${{ secrets.GIT_API_KEY }}
        run: |
          python "ccq-utils/github scripts/repo_undefined_monthly.py"

      - name: Upload latest report
        uses: actions/upload-artifact@v2
        with:
          name: undefined-repo-owner-report
          path: ccq-utils/github scripts/output/undefined_repo_owner_latest.xlsx
          retention-days: 30
