name: Leaked Secrets Scan

on:
  workflow_call:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Entire Git history of the repository will be fetched
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.81.8
        with:
          extra_args: --debug --only-verified # Check only for verified secrets
