name: Leaked Secrets Scan

on:
  workflow_call:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Entire Git history of the repository will be fetched
      - name: Create exclusions file
        run: |
          cat << EOF > trufflehog_exclusions.txt
          \.env\.example$
          EOF
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.81.8
        with:
          extra_args: --debug --only-verified --exclude-paths trufflehog_exclusions.txt # Check only for verified secrets
